version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5001:5001
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - myback
    restart: always
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - myback
  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - myback
  flask:
    build:
      context: ../../CV/burlamask_cv
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - myback

volumes:
  pgdata:

networks:
  myback:
    driver: bridge